config/routes.rb
Basecamp::Application.routes.draw do

  get "events/index"

  get "events/show"

 root :to => 'projects#index'

  resources :tags do
    collection do
      put :delete_all
    end
  end
 match 'message/:id/comments', :to => 'comments#index_message', :as => "message_comments"
 match 'message/:id/new', :to => 'messages#new', :as => "new_project_message"
 match 'project/:id/comments', :to => 'comments#index_project', :as => "project_comments"
 match 'project/:id/message_comments', :to => 'comments#index_message_comments', :as => "project_message_comments"
 match 'project/:id/task_comments', :to => 'comments#index_task_comments', :as => "project_task_comments"
 match 'task/:id/comments',    :to => 'comments#index_task', :as => "task_comments"
 match 'project/:id/messages', :to => 'messages#index', :as => "project_messages"
 match 'project/:id/events', :to => 'events#index', :as => "project_events"
 match 'project/:id/tasks',    :to => 'tasks#index', :as => "project_tasks"
 match 'projects/basecamp', :to => 'projects#index_basecamp', :as => "basecamp_projects"
 match 'message/:id/add_comment', :to => 'comments#add_comment', :as => "add_message_comment"
 match 'project/:id/disconnect',    :to => 'projects#disconnect', :as => "disconnect_project"

 resources :comments
 resources :messages
 resources :tasks
 resources :projects
 resources :words
 resources :tags
 resources :events
 resources :auths

 match 'auths/select', :to => 'auths#select'
 match 'task/:id/import', :to => 'tasks#import', :as => "import_task"
 match 'task/:id/reimport', :to => 'tasks#reimport', :as => "reimport_task"
 match 'tasks/:id/import', :to => 'tasks#import_all', :as => "import_tasks"
 match 'tasks/:id/discover', :to => 'tasks#discover', :as => "discover_tasks"
 match 'tasks/:id/destroy', :to => 'tasks#destroy', :as => "project_delete_tasks"

 match 'comment/:id/import_for_message', :to => 'comments#import_for_message', :as => "import_comments_for_message"
 match 'comment/:id/reimport', :to => 'comments#reimport', :as => "reimport_comment"
 match 'comments/:id/import', :to => 'comments#import_all', :as => "import_comments"
 match 'comments/:id/discover', :to => 'comments#discover', :as => "discover_comments"
 match 'comments/:id/tag', :to => 'comments#tag'
 match 'comment/:id/remove_tag', :to => 'comments#remove_tag', :as => "remove_comment_tag"
 match 'comments/:id/destroy_message_comments', :to => 'comments#destroy_message_comments', :as => "project_delete_message_comments"
 match 'comments/:id/destroy_task_comments', :to => 'comments#destroy_task_comments', :as => "project_delete_task_comments"
 match 'comment/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_message_comments"
 match 'comment/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_task_comments"
 match 'comment/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_message_comments"

 match 'message/:id/import', :to => 'messages#import', :as => "import_message"
 match 'message/:id/reimport', :to => 'messages#reimport', :as => "reimport_message"
 match 'messages/:id/import', :to => 'messages#import_all', :as => "import_messages"
 match 'messages/:id/reimport', :to => 'messages#reimport_all', :as => "reimport_messages"
 match 'messages/:id/discover', :to => 'messages#discover', :as => "discover_messages"
 match 'messages/:id/tag', :to => 'messages#tag'
 match 'message/:id/remove_tag', :to => 'messages#remove_tag', :as => "remove_message_tag"
 match 'messages/:id/destroy', :to => 'messages#destroy', :as => "project_delete_messages"
 
 match 'event/:id/import', :to => 'events#import', :as => "import_event"
 match 'event/:id/reimport', :to => 'events#reimport', :as => "reimport_event"
 match 'event/:id/import_all', :to => 'events#import_all', :as => "import_events"
 match 'event/:id/reimport', :to => 'events#reimport_all', :as => "reimport_events"
 match 'event/:id/discover', :to => 'events#discover', :as => "discover_events"
 match 'events/:id/destroy', :to => 'events#destroy', :as => "project_delete_events"

 match 'project/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_project_message_comments"
 match 'project/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_project_message_comments"
 match 'project/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_project_task_comments"
 match 'project/:id/discover_task_comments', :to => 'comments#discover_task_comments', :as => "discover_project_task_comments"
 match 'project/:id/import', :to => 'projects#import', :as => "import_project"
 match 'project/:id/reimport', :to => 'projects#reimport', :as => "reimport_project"
 match 'projects/import', :to => 'projects#import_all', :as => "import_projects"
 match 'projects/discover', :to => 'projects#discover', :as => "discover_projects"
 match 'project/:id/refresh_available_messages', :to => 'projects#get_available_messages', :as => "refresh_available_messages"
 match 'project/:id/refresh_available_events', :to => 'projects#get_available_events', :as => "refresh_available_events"
 match 'project/:id/refresh_available_tasks', :to => 'projects#get_available_tasks', :as => "refresh_available_tasks"
 

end

app/models/message.rb
class Message < ActiveRecord::Base
  
  belongs_to :project
  has_many :comments, :dependent => :destroy
  has_many :attachments, :dependent => :destroy
  has_many :comment_tags, :through => :comments, :source => :tags
  has_many :message_taggings
  has_many :tags, :through => :message_taggings

  
  def self.get_count(proj)
    proj.messages.count
  end  
  
  def self.get_bc_count(proj, from_bc = false)
    num = 0
    if proj.basecamp_id   
      if from_bc
        messages = get_all_bc_messages_in_project(proj)
        num = messages.count
        proj.available_messages = num
        proj.save!
      else
        num = proj.available_messages
      end
    end
    num
  end
  
  def self.get_all_bc_messages_in_project(proj)
    #Basecamp::Message.find(:all, :params => { :project_id => proj.basecamp_id }, :from => :archive)
    Basecamp::Message.archive(proj.basecamp_id)
  end
  
  def self.import_all_from_basecamp_project(project)
    Message.destroy_all(:project_id => project.id)
    bc_list = get_all_bc_messages_in_project(project)
    bc_list.each do |bcm|
      msg = Basecamp::Message.find(bcm.id)
      message = project.messages.build
      message.copy_fields_from_basecamp(msg)
      if !message.save!
        return false
      end
      sleep 1
     end
    true
  end
    
  def self.destroy_project_messages(project)
     Message.destroy_all(:project_id => project.id)
  end
  
  def self.discover_new_from_basecamp(project)
   # bc_list = Basecamp::Message.find(:all, :params => { :project_id => project.basecamp_id}, :from => :archive)
   bc_list = get_all_bc_messages_in_project(project)
   bc_list.each do |bcm|
      if !find_by_basecamp_id(bcm.id)
        msg = project.messages.build
        m=Basecamp::Message.find(bcm.id)
        msg.copy_fields_from_basecamp(m)
        if !msg.save!
          return false
        end
        sleep 1
        #Comment.discover_new_from_basecamp_message(bcm.id)
       
      end 
    end
    true
  end


      
  def copy_fields_from_basecamp(basecamp_message, summary=false)
    self.title = basecamp_message.title
    self.posted_on = basecamp_message.posted_on
    self.commented_on = basecamp_message.commented_at
    self.basecamp_id = basecamp_message.id
    if !summary
      self.content = basecamp_message.body
      self.author = basecamp_message.author_name
      if !basecamp_message.attachments.empty?
        self.attachments.destroy_all
        return copy_attachments_from_basecamp(basecamp_message.attachments)
      end
    end
    true
  end  

  def copy_attachments_from_basecamp(basecamp_attachments)
    basecamp_attachments.each do |a|      
      attachment = self.attachments.build
      attachment.copy_fields_from_basecamp(a)
      if !attachment.save!
        return false
      end
    end
    self.num_attachments = basecamp_attachments.count
    return true
  end  
  
  def add_tag_numbers(tag_numbers)
    ts = tags + comment_tags 
    ts.each do |t|
      if tag_numbers[:tag_id => t.id].nil?
        tag_numbers[:tag_id => t.id] = 1
      else
        tag_numbers[:tag_id => t.id] += 1
      end
    end
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include   MessagesHelper
  include   ApplicationHelper
  
  helper_method :sort_column, :sort_direction

  def index
    @project = Project.find(params[:id])    

    @per_page = params[:per_page] ||  20
    order_str = sort_column + " "  + sort_direction
    @messages = @project.messages.order(order_str).page(params[:page]).per_page(@per_page)
    add_tag_numbers_across_messages(@messages)
    @tags = (@project.message_tags + @project.message_comment_tags + @project.task_comment_tags).uniq
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  def new
    @project = Project.find(params[:id])
    @message = Message.new
  end
  
  def create
    @project = Project.find(params[:id])
    @message = @project.messages.build(params[:message])
    if !@message.save!
      flash.now[:error] = "Error creating note"
      render 'new'
    else
      redirect_to project_messages_path(@project), :notice => "Created note"     
    end
  end
  
  def edit
    @message = Message.find(params[:id])  
    @project = @message.project
  end
  
  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(params[:message])
      flash.now[:success] = "Updated note"
    else
      flash.now[:error] = "Error updating note"
    end
    render 'edit'
  end
  
  def tag
    @added = false
    message = Message.find(params[:id])
        
    t = Tag.find_or_create_tag(params[:new_tag])
    if !t
      @tag_message = "Tag must be at least 2 characters long"
    else
      if message.tags.include? t
        @tag_message = "Already have that tag"
      else    
        t.update_attribute(:last_used_at, Time.now.utc)   
        message.tags << t
        @tag_message = "Added tag"
        @added = true
      end
    end
    @tags = message.tags 
    @new_tag = t
  end
  
  def remove_tag
    @removed = false
    tag_id = params[:tag_id]
    message = Message.find(params[:id])
    tag = message.tags.find(tag_id)
    rescue
      @tag_message = "Not able to remove tag"
    else
      message.tags.delete(tag)  
      @removed = true
      @remove_tag = tag_id
      @tags = message.tags
  end
    
  def show
    @message = Message.find(params[:id])
    if @message.content.nil?
      @message.content = ""
    end
    if @message.basecamp_id && !@message.comments
      comments = Basecamp::Comment.find(:all, :params => { :post_id => @message.basecamp_id })
    else
      comments = @message.comments
    end
    @actions = get_actions(@message.content)
    @events = get_events(@message.content)
    @tags = @message.tags
    @all_tags = @message.project.message_tags.uniq
    #@questions = get_questions @message.content
    @num_comments = comments.nil? ? 0 : comments.count
    @comment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  def import_all
    project = Project.find(params[:id])
    if Message.import_all_from_basecamp_project(project)
      flash[:success] = "Imported messages successfully"
    else
      flash[:error] = "There was a problem importing the messages"
    end
    redirect_to project_path(project.id)
  end
 
  def import
    message = copy_message_from_basecamp Basecamp::Post.find(params[:id])
    if message.save!
      flash[:success] = "Imported message successfully"
    else
      flash[:error] = "There was a problem importing the message"
    end
    redirect_to project_messages_path(message.project_id)
  end
  
  def reimport
    message = Message.find(params[:id])
    message.copy_fields_from_basecamp(Basecamp::Message.find(message.basecamp_id))    
    if message.save!
      flash[:success] = "Re-Imported message successfully"
    else
      flash[:error] = "There was a problem re-importing the message"
    end
    redirect_to project_messages_path(message.project_id)
  end
  
  def destroy
    project = Project.find(params[:id])
    Message.destroy_project_messages(project)    
    redirect_to project_path(project), :notice => "Removed messages"     
  end
  
  def discover
    project = Project.find(params[:id])
    startnum = project.messages.count
    if !Message.discover_new_from_basecamp(project)
      redirect_to project_messages_path(params[:id]), :error => "Error importing new messages"
    end
    additional_num = project.messages.count-startnum
    redirect_to project_path(params[:id]), :notice => additional_num > 0 ? "Successfully imported #{additional_num} new messages" : "No new messages to import"
  end  
  
  private
   
  def add_tag_numbers_across_messages(messages)
    tag_num = {}
    tags = []
    messages.each do |m|
      tags = (tags + m.tags + m.comment_tags).uniq
      m.add_tag_numbers(tag_num)
    end
    
    @tag_numbers = tag_num
    @tags = tags
  end
  
  def sort_column
      Message.column_names.include?(params[:sort]) ? params[:sort] : "posted_on"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  
  include ActionView::Helpers::SanitizeHelper 
  

end

app/views/messages/_edit.html.erb
<%= form_for @message do |f| %>

	<%= f.label 'Title' %>	
	<%= f.text_field :title %><br/>
	<%= f.label 'Content' %>	
	<%= f.text_area :content %><br/>
	<%= f.submit %>
<%= hidden_field_tag "id", @project.id %>
	
<% end %>

app/views/messages/_message.html.erb
  <tr>
<% if message.basecamp_id || message.num_comments %>
    <td ><%= message.id.nil? ? message.title : link_to(message.title, message_path(message)) %></td>
    <td style="text-align: center"><%= message.num_comments %></td>
    <td style="text-align: center"><%= message.num_attachments %></td>
    <td style="width: 150px"><%= message.posted_on.to_formatted_s(:long) %></td>
    <td><% if message.project.basecamp_id %> 
    	<%= message.id.nil? ? link_to('Import', import_message_path(message)) : link_to('Re-Import', reimport_message_path(message)) %>
    	<% end %> 
    </td>
<% else %>
    <td><%= link_to(message.title, message_path(message)) %></td>
    <td style="text-align: center"><%= message.comments.count==0 ? "0" : link_to(message.comments.count, message_comments_path(message)) %></td>
    <td style="width: 150px"><%= message.created_at.to_formatted_s(:long) %></td>
    <td style="width: 150px"><%= message.updated_at.to_formatted_s(:long) %></td>
<% end %>
  </tr>

app/views/messages/edit.html.erb
<%= render 'edit', :many => false %>

<%= link_to "All messages", project_messages_path(@project) %>

app/views/messages/index.html.erb
<h1>Messages for Project '<%=@project.name%>'</h1>


<%= will_paginate @messages, :class => 'flickr_pagination' %>

<table class="cloud-and-table">
	<tr>
		<td width="15%">
			<table id="tag-list" class="url-list sortable">
  			<tr>
    			<th id="cloud-header">Tag Cloud</th>
			</tr>
			<tr >
				<td style="padding: 5px">
					<%= render 'tags/tag_cloud', :tags => @tags, :tag_numbers => @tag_numbers %>
				</td>
			</tr>
			</table>	
		</td>
		<td>
			<table id="table-list" class="url-list sortable">
  			<tr>
    			<th id="list-header">Title</th>
    			<% if @project.basecamp_id %>
	    			<th><%= sortable("num_comments", "Comments?") %></th>
	    			<th><%= sortable("num_attachments", "Attachments?") %></th>
    				<th><%= sortable("posted_on", "Posted") %> </th>
    			<% else %>
	    			<th>Num Comments</th>
      				<th><%= sortable("created_at", "Created") %> </th>
      				<th><%= sortable("updated_at", "Updated") %> </th>
				<% end %>
    			<th></th>
  			</tr>
				<%= render @messages %>
			</table>
		</td>	
	</tr>
</table>
<% if @project.basecamp_id %>
<%=  button_to "(Re-)Import All", import_messages_path(@project), :confirm =>"Are you sure?  All messages for this project will be deleted first...", :class => 'inline' %>
<%=  button_to "Discover new", discover_messages_path(@project)%>
<%= link_to "Project", project_path(@project)%> |
<%= link_to "All Projects", basecamp_projects_path %> 
<% else %>
<%= button_to "Create Note", new_project_message_path(@project.id), :method => 'get' %>
<%= link_to "Project", project_path(@project)%> |
<%= link_to "All Projects", projects_path %> 
<% end %>

<script>
	$('#tag-list').height($('#table-list').height());
	$('#cloud-header').height($('#list-header').height());
	
</script>

app/views/messages/new.html.erb
<%= render 'edit' %>

<%= link_to "All messages", project_messages_path(@project) %>

app/views/messages/remove_tag.js.erb
<% if @removed %>
	$('#tag-header').text('Tags (<%= @tags.count %>)');
	$('#tag-header').effect("highlight", {}, 2000);
	$('#<%= @remove_tag %>').remove();
<% else %>
  alert('<%= @tag_message %>');
<% end %>

app/views/messages/show.html.erb
<table>

<tr>
	<td><b>Title:</b></td>
	<td><%= @message.title %></td>
</tr>

<% if @message.basecamp_id %>
<tr>
	<td><b>Author:</b></td>
  	<td><%= @message.author %></td>
</tr>
<tr>
	<td><b>Posted:</b></td>
  	<td><%= @message.posted_on %></td>
</tr>
<% else %>
<tr>
	<td><b>Created:</b></td>
  	<td><%= @message.created_at %></td>
</tr>
<% end %>
<tr>
	<td><b>Comments:</b></td>
	<td id="comment-count">
  <% if @num_comments>0 %>
    <%= link_to(@num_comments, message_comments_path(@message.id), :id => 'num-comments') %>
  <% else %>
    <span id="no-comments">None</span>
  <% end %>
	</td>
</tr>
<tr>
	<td><b>Attachments:</b></td>
	<td>
  <% if @message.attachments.empty? %>
     None
  <% else
     @message.attachments.each do |a| %>
     	<%= link_to("#{a.name} (#{a.attachment_type})", "#{a.basecamp_url}") %> |
     <%	end %>
  <% end %>
	</td>
</tr>
<% if @message.basecamp_id %>
<tr>
	<td><b>Basecamp ID:</b></td>
  	<td><%= @message.basecamp_id %></td>
</tr>
<% end %>
</table>
</p>


<% 
actions_text = ""
@actions.each_with_index do |a,i| 
  actions_text += "#{i+1}.\t#{a}\n" 
end 
events_text = ""
@events.each_with_index do |e,i| 
  events_text += "#{i+1}.\t#{e}\n" 
end 
%>


<div id="wrapper">
    <ul class="tabs">
        <li><a href="javascript:void(0)" class="defaulttab" rel="tabs1">HTML View</a></li>
        <li><a href="javascript:void(0)" rel="tabs2">Raw Content</a></li>
        <li><a href="javascript:void(0)" rel="tabs3">Stripped of Tags</a></li>
        <li><a href="javascript:void(0)" rel="tabs4">Actions (<%= @actions.count %>)</a></li>
        <li><a href="javascript:void(0)" rel="tabs5">Events (<%= @events.count %>)</a></li>
        <li><a href="javascript:void(0)"  rel="tabs6"><span id="tag-header">Tags (<%= @tags.count %>)</span></a></li>
    </ul>
  
  <%= render 'tags/add_tag', :id => @message.id, :controller => "messages", :all_tags => @all_tags %>

    <div class="tab-content" id="tabs1"><div id="htmlpreview" class="html"><%= raw @message.content %></div></div>
    <div class="tab-content" id="tabs2"><textarea class="raw"><%= @message.content %></textarea> </div>
    <div class="tab-content" id="tabs3">
    	<textarea class="stripped"><%= raw strip_tags(@message.content.gsub(/&nbsp;/i," ").gsub(/<div class=\"paragraph\_break\"/i,"&#013; &#010;<div ")) %></textarea> 
    </div>
    <div class="tab-content" id="tabs4"><textarea class="stripped"><%= actions_text %></textarea></div>
    <div class="tab-content" id="tabs5"><textarea class="stripped"><%= events_text %></textarea></div>
    <div class="tab-content" id="tabs6"><%= render 'tags/tag_list', :tags => @tags, :id => @message.id, :controller => "messages"%>

    </div>
</div>  
  


</p>

<% if !@message.basecamp_id %>
	<%= render 'comments/add_comment', :message_id => @message.id, :comment => @comment %>
<% end %>

<%= link_to 'All Messages', project_messages_path(@message.project_id) %>

app/views/messages/tag.js.erb
<% if @added %>
	$('#tag-header').text('Tags (<%= @tags.count %>)');
	$('#tag-header').effect("highlight", {}, 3000);
	<% tag_id = @new_tag.id %>
	$('#tag-list li:last').after('<li id="<%= tag_id %>"><%= link_to @new_tag.name, tag_path(tag_id), :class => "price-tag-link" %><%= link_to "X", {:controller => "messages", :action => "remove_tag", :tag_id => tag_id}, {:id => "popup-#{tag_id}", :class => "popup", :remote => true }%>');
<% else %>
  alert('<%= @tag_message %>');
<% end %>

$("form#new-tag-form")[0].reset();	
$("#new_tag").focus();