config/routes.rb
Basecamp::Application.routes.draw do

  get "events/index"

  get "events/show"

 root :to => 'projects#index'

  resources :tags do
    collection do
      put :delete_all
    end
  end
 match 'message/:id/comments', :to => 'comments#index_message', :as => "message_comments"
 match 'message/:id/new', :to => 'messages#new', :as => "new_project_message"
 match 'project/:id/comments', :to => 'comments#index_project', :as => "project_comments"
 match 'project/:id/message_comments', :to => 'comments#index_message_comments', :as => "project_message_comments"
 match 'project/:id/task_comments', :to => 'comments#index_task_comments', :as => "project_task_comments"
 match 'task/:id/comments',    :to => 'comments#index_task', :as => "task_comments"
 match 'project/:id/messages', :to => 'messages#index', :as => "project_messages"
 match 'project/:id/events', :to => 'events#index', :as => "project_events"
 match 'project/:id/tasks',    :to => 'tasks#index', :as => "project_tasks"
 match 'projects/basecamp', :to => 'projects#index_basecamp', :as => "basecamp_projects"
 match 'message/:id/add_comment', :to => 'comments#add_comment', :as => "add_message_comment"
 match 'project/:id/disconnect',    :to => 'projects#disconnect', :as => "disconnect_project"

 resources :comments
 resources :messages
 resources :tasks
 resources :projects
 resources :words
 resources :tags
 resources :events
 resources :auths

 match 'auths/select', :to => 'auths#select'
 match 'task/:id/import', :to => 'tasks#import', :as => "import_task"
 match 'task/:id/reimport', :to => 'tasks#reimport', :as => "reimport_task"
 match 'tasks/:id/import', :to => 'tasks#import_all', :as => "import_tasks"
 match 'tasks/:id/discover', :to => 'tasks#discover', :as => "discover_tasks"
 match 'tasks/:id/destroy', :to => 'tasks#destroy', :as => "project_delete_tasks"

 match 'comment/:id/import_for_message', :to => 'comments#import_for_message', :as => "import_comments_for_message"
 match 'comment/:id/reimport', :to => 'comments#reimport', :as => "reimport_comment"
 match 'comments/:id/import', :to => 'comments#import_all', :as => "import_comments"
 match 'comments/:id/discover', :to => 'comments#discover', :as => "discover_comments"
 match 'comments/:id/tag', :to => 'comments#tag'
 match 'comment/:id/remove_tag', :to => 'comments#remove_tag', :as => "remove_comment_tag"
 match 'comments/:id/destroy_message_comments', :to => 'comments#destroy_message_comments', :as => "project_delete_message_comments"
 match 'comments/:id/destroy_task_comments', :to => 'comments#destroy_task_comments', :as => "project_delete_task_comments"
 match 'comment/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_message_comments"
 match 'comment/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_task_comments"
 match 'comment/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_message_comments"

 match 'message/:id/import', :to => 'messages#import', :as => "import_message"
 match 'message/:id/reimport', :to => 'messages#reimport', :as => "reimport_message"
 match 'messages/:id/import', :to => 'messages#import_all', :as => "import_messages"
 match 'messages/:id/reimport', :to => 'messages#reimport_all', :as => "reimport_messages"
 match 'messages/:id/discover', :to => 'messages#discover', :as => "discover_messages"
 match 'messages/:id/tag', :to => 'messages#tag'
 match 'message/:id/remove_tag', :to => 'messages#remove_tag', :as => "remove_message_tag"
 match 'messages/:id/destroy', :to => 'messages#destroy', :as => "project_delete_messages"
 
 match 'event/:id/import', :to => 'events#import', :as => "import_event"
 match 'event/:id/reimport', :to => 'events#reimport', :as => "reimport_event"
 match 'event/:id/import_all', :to => 'events#import_all', :as => "import_events"
 match 'event/:id/reimport', :to => 'events#reimport_all', :as => "reimport_events"
 match 'event/:id/discover', :to => 'events#discover', :as => "discover_events"
 match 'events/:id/destroy', :to => 'events#destroy', :as => "project_delete_events"

 match 'project/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_project_message_comments"
 match 'project/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_project_message_comments"
 match 'project/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_project_task_comments"
 match 'project/:id/discover_task_comments', :to => 'comments#discover_task_comments', :as => "discover_project_task_comments"
 match 'project/:id/import', :to => 'projects#import', :as => "import_project"
 match 'project/:id/reimport', :to => 'projects#reimport', :as => "reimport_project"
 match 'projects/import', :to => 'projects#import_all', :as => "import_projects"
 match 'projects/discover', :to => 'projects#discover', :as => "discover_projects"
 match 'project/:id/refresh_available_messages', :to => 'projects#get_available_messages', :as => "refresh_available_messages"
 match 'project/:id/refresh_available_events', :to => 'projects#get_available_events', :as => "refresh_available_events"
 match 'project/:id/refresh_available_tasks', :to => 'projects#get_available_tasks', :as => "refresh_available_tasks"
 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include   ApplicationHelper

  helper_method :sort_column, :sort_direction
  
  def index_message
    @per_page = params[:per_page] ||  20
    order_str = sort_column + " "  + sort_direction
    @message = Message.find(params[:id])    
    @comments = @message.comments.order(order_str).page(params[:page]).per_page(@per_page)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  def index_task
    @per_page = params[:per_page] ||  20
    order_str = sort_column + " "  + sort_direction
    @task = Task.find(params[:id])    
    @comments = @task.comments.order(order_str).page(params[:page]).per_page(@per_page)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  def index_project
    @per_page = params[:per_page] ||  20
    @project = Project.find(params[:id])
    order_str = sort_column + " "  + sort_direction
#    @comments = []
    @comments = Comment.joins( "LEFT JOIN `messages` ON `messages`.`id` = `comments`.`message_id` LEFT JOIN `tasks` ON `tasks`.`id` = `comments`.`task_id`")
                       .where([ "messages.project_id = #{params[:id]} or tasks.project_id = #{params[:id]}" ]).order(order_str).page(params[:page]).per_page(@per_page)      
#    @comments << (@project.message_comments+@project.task_comments).order(order_str).page(params[:page]).per_page(@per_page)      
    #@comments << @project.task_comments#.order(order_str).page(params[:page]).per_page(@per_page)      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end
  
  def index_message_comments
    @per_page = params[:per_page] ||  20
    @project = Project.find(params[:id])
    order_str = sort_column + " "  + sort_direction
    @comments = Comment.joins( "LEFT JOIN `messages` ON `messages`.`id` = `comments`.`message_id`")
                       .where([ "messages.project_id = #{params[:id]}"]).order(order_str).page(params[:page]).per_page(@per_page)      
#    @comments << (@project.message_comments+@project.task_comments).order(order_str).page(params[:page]).per_page(@per_page)      
    #@comments << @project.task_comments#.order(order_str).page(params[:page]).per_page(@per_page)      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end
  
  def index_task_comments
    @per_page = params[:per_page] ||  20
    @project = Project.find(params[:id])
    order_str = sort_column + " "  + sort_direction
    @comments = Comment.joins( "LEFT JOIN `tasks` ON `tasks`.`id` = `comments`.`task_id`")
                       .where([ "tasks.project_id = #{params[:id]}"]).order(order_str).page(params[:page]).per_page(@per_page)      
#    @comments << (@project.message_comments+@project.task_comments).order(order_str).page(params[:page]).per_page(@per_page)      
    #@comments << @project.task_comments#.order(order_str).page(params[:page]).per_page(@per_page)      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  def index
    @per_page = params[:per_page] ||  20
    @project = Project.find(params[:id])
    
    @comments = @project.comments 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end

  end
  
  def show
    @comment = Comment.find(params[:id])
    @message = @comment.message
    #@task = @comment.task
    @task = nil
    @actions = get_actions(@comment.content)
    @events = get_events(@comment.content)
    @tags    = @comment.tags
    @all_tags = ""
    if @message || @task
      project = @message ? @message.project : @task.project 
      @all_tags = (project.message_comment_tags + project.task_comment_tags).uniq
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  def new
    @message = Message.find(params[:id])
    @comment = Comment.new
  end
  
  def create
    @message = Message.find(params[:id])
    @comment = @message.comments.build(params[:comment])
    if !@comment.save!
      flash.now[:error] = "Error creating comment"
      render 'new'
    else
      redirect_to message_comments_path(@message), :notice => "Created comment"     
    end
  end
  
  def destroy
    comment = Comment.find(params[:id])
    @id = params[:id]
    comment.destroy
  end
    
  def destroy_message_comments
    project = Project.find(params[:id])
    project.message_comments.each do |c| 
      c.destroy
    end
    redirect_to project_path(params[:id]), :notice => "Deleted message comments"     
  end

  def destroy_task_comments
    project = Project.find(params[:id])
    project.task_comments.each do |c| 
      c.destroy
    end
    redirect_to project_path(params[:id]), :notice => "Deleted task comments"     
  end
  
  def add_comment
    @message = Message.find(params[:id])
    @comment = @message.comments.build(params[:comment])
    @added = false
    if !@comment.save!
      @msg = "Error creating comment"
    else
      @msg = "Added comment"
      @added = true
    end
    @num_comments = @message.comments.count
  end

  def edit
    @comment = Comment.find(params[:id])  
  end
  
  def update
    @comment = Comment.find(params[:id])  
    if @comment.update_attributes(params[:comment])
      flash.now[:success] = "Updated comment"
    else
      flash.now[:error] = "Error updating comment"
    end
    render 'edit'
  end
  
  def tag
    @added = false
    comment = Comment.find(params[:id])  
        
    t = Tag.find_or_create_tag(params[:new_tag])
    if !t
      @tag_message = "Tag must be at least 2 characters long"
    else
      if comment.tags.include? t
        @tag_message = "Already have that tag"
      else        
        t.update_attribute(:last_used_at, Time.now.utc)   
        comment.tags << t
        @tag_message = "Added tag"
        @added = true
      end
    end
    @tags = comment.tags 
    @new_tag = t
  end
  
  def remove_tag
    @removed = false
    tag_id = params[:tag_id]
    comment = Comment.find(params[:id])  
    tag = comment.tags.find(tag_id)
    rescue
      @tag_message = "Not able to remove tag"
    else
      comment.tags.delete(tag)  
      @removed = true
      @remove_tag = tag_id
      @tags = comment.tags
  end
  
  def import_all_for_project
    project = Project.find(params[:id])
    if !import_all_for_project(params[:id])
      flash[:error] =  "There was a problem importing the comments"
    else
      flash[:success] =  "Comments imported successfully"
    end
    redirect_to project_comments_path(project.id)
  end

  def import_message_comments
    project = Project.find(params[:id])
    if !project.messages.nil?
      err = false
      project.messages.each do |m|
        if err || !Comment.import_all_from_basecamp_message(m)
          flash[:error] = "Problem importing comments for message id #{m.id}"
          err = true
        else
          flash[:success] = "Successfully imported message comments"
        end
        sleep 1
      end
    else
      flash[:error] = "No message comments to import"
    end
    redirect_to project_path(params[:id])
  end

  def import_task_comments
    project = Project.find(params[:id])
    if !project.tasks.nil?
      err = false
      project.tasks.each do |t|
        if err || !Comment.import_all_from_basecamp_task(t)
          flash[:error] = "Problem importing comments for task id #{m.id}"
          err = true
        else
          flash[:success] = "Successfully imported task comments"
        end
        sleep 1
      end
    else
      flash[:error] = "No task omments to import"
    end
    redirect_to project_path(params[:id])
  end

  def import_all_for_message
    if Comment.import_all_from_basecamp_message(Message.find(params[:id]))
      flash[:success] = "Imported comments successfully"
    else
      flash[:error] = "There was a problem importing the comments"
    end
    redirect_to message_comments_path(params[:id])
  end

  def import_all_for_task
    if Comment.import_all_from_basecamp_task(Task.find(params[:id]))
      flash[:success] = "Imported comments successfully"
    else
      flash[:error] = "There was a problem importing the comments"
    end
    redirect_to task_comments_path(params[:id])
  end

  def import
    comment.copy_fields_from_basecamp Basecamp::Comment.find(params[:id])
    if comment.save!
      flash[:success] = "Imported comment successfully"
    else
      flash[:error] = "There was a problem importing the comment"
    end
    redirect_to message_comments_path(comment.message)
  end
  
  def reimport
    comment = Comment.find(params[:id])
    comment.copy_fields_from_basecamp(Basecamp::Comment.find(comment.basecamp_id))    
    if comment.save!
      flash[:success] = "Re-Imported comment successfully"
    else
      flash[:error] = "There was a problem re-importing the comment"
    end
    redirect_to message_comments_path(comment.message)
  end
  
  private
  
  
  # imports only comments for already imported messages and tasks
  def import_all_for_project(project_id)
    Comment.import_all_for_project(project_id)
  end

  # def copy_comment_from_basecamp basecamp_comment, com_list=nil
    # if !com_list.nil?
      # com_list.each do |c|
        # if c.basecamp_id == basecamp_comment.id
          # return nil
        # end
      # end
    # end
    # comment = Comment.new
    # comment.copy_fields_from_basecamp(basecamp_comment)
  # end

  

  def sort_column
      Comment.column_names.include?(params[:sort]) ? params[:sort] : "posted_on"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_add_comment.html.erb
<%= form_for comment, :url => add_message_comment_path, :remote => true do |f| %>
	<%= f.text_area :content, :class => "add-comment" %><br/>
	<%= f.submit "Add Comment" %>
	<%= hidden_field_tag "id", message_id %>
<% end %>

app/views/comments/_comment.html.erb
<% stripped_c = strip_tags(comment.content.gsub(/&nbsp;/i," ").gsub(/<div class=\"paragraph\_break\"/i,"&#013; &#010;<div ")) %>
  <tr id="<%= comment.id %>">
  <% if comment.basecamp_id %>
    <td><%= comment.id.nil? ? comment.author : link_to(comment.author, comment_path(comment))%></td>
    <td><%= raw stripped_c.size<=100 ? stripped_c : "#{stripped_c[0..100]}..." %></td>
    <% if !comment.message.nil? %>
    <td><%= link_to "Message #{comment.message.id}", message_path(comment.message.id) %></td>
    <% elsif !comment.task.nil? %>
    <td><%= link_to "Task #{comment.task.id}", task_path(comment.task.id) %></td>
    <% end %>
    <td><%= comment.num_attachments %></td>
    <td><%= comment.posted_on.to_formatted_s(:long) %></td>
    <td><%= comment.id.nil? ? link_to('Import', import_comment_path(comment)) : link_to('Re-Import', reimport_comment_path(comment)) %></td>
  <% else %>
    <td><%= link_to(stripped_c.size<=100 ? stripped_c : "#{stripped_c[0..100]}...", comment_path(comment)) %></td>
    <td><%= comment.num_attachments %></td>
    <td><%= comment.created_at.to_formatted_s(:long) %></td>
    <td><%= link_to "Delete", comment_path(comment), :confirm => "Are you sure?", :method => "delete", :remote => true %></td>
  <% end %>
  </tr>

app/views/comments/_edit.html.erb
<%= form_for @comment do |f| %>

	<%= f.label 'Content' %>	
	<%= f.text_area :content %><br/>
	<%= f.submit %>
	<%= hidden_field_tag "id", @comment.message.id %>
	
<% end %>

app/views/comments/add_comment.js.erb
<% if @added %>
	<% if @num_comments==1 %>
		$('#comment-count').append('<%= link_to(@num_comments, message_comments_path(@message.id), :id => "num-comments") %>');
		$("#no-comments").remove();
	<% else %>
		$('#num-comments').text('<%= @num_comments %>');
	<% end %>
	$('#num-comments').effect("highlight", {}, 3000);
	$("form#new_comment")[0].reset();	
<% else %>
  alert('<%= @tag_message %>');
<% end %>

app/views/comments/edit.html.erb
<%= render 'edit' %>

<%= link_to "All comments", message_comments_path(@message) %>

app/views/comments/index.html.erb
<h1>
	All Comments for Project '<%= @project.name%>'
</h1>
<%= will_paginate @comments, :class => 'flickr_pagination' %>
<table class="url-list sortable">
  <tr>
  <% if @project.basecamp_id %>
    <th>Author</th>
    <th>Content</th>
    <th>Message/Task</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('posted_on', 'Posted') %></th>
    <th></th>
  <% else %>
    <th>Content</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('created_at', 'Created') %></th>
    <th></th>
  <% end %>
  </tr>
<%= render @comments %>

</table>

<%= link_to "Project", project_path(@project)%>

app/views/comments/index_message.html.erb
<h1>
	All Comments for Message '<%=@message.title%>'
</h1>
<%= will_paginate @comments, :class => 'flickr_pagination' %>
<table class="url-list sortable">
  <tr>
  <% if @message.basecamp_id %>
    <th>Author</th>
    <th>Content</th>
    <th>Message Id</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('posted_on', 'Posted') %></th>
    <th></th>
  <% else %>
    <th>Content</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('created_at', 'Created') %></th>
    <th></th>
  <% end %>
  </tr>
<%= render @comments %>

</table>
<% if @message.basecamp_id %>
	<%=  button_to "(Re-)Import All", import_message_comments_path(@message), :confirm => "Warning: all existing comments for this message will be deleted first!" %>
<% else %>
	<%=  button_to "Add Comment", add_message_comment_path(@message) %>
<% end %>

<%= link_to "Message", message_path(@message.id)%> |
<%= link_to "All Messages", project_messages_path(@message.project_id)%> |
<%= link_to "Project", project_path(@message.project_id)%>

app/views/comments/index_message_comments.html.erb
<h1>
	All Message Comments for Project '<%= @project.name %>'
</h1>
<%= will_paginate @comments, :class => 'flickr_pagination' %>
<table class="url-list sortable">
  <tr>
    <th>Author</th>
    <th>Content</th>
    <th>Message Id</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('posted_on', 'Posted') %></th>
    <th></th>
  </tr>
<%= render @comments %>
</table>

<%= link_to "All Messages", project_messages_path(@project)%> |
<%= link_to "All Tasks", project_tasks_path(@project)%> |
<%= link_to "Project", project_path(@project)%>

app/views/comments/index_project.html.erb
<h1>
	All Comments for Project '<%= @project.name %>'
</h1>
<%= will_paginate @comments, :class => 'flickr_pagination' %>
<table class="url-list sortable">
  <tr>
    <th>Author</th>
    <th>Content</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('posted_on', 'Posted') %></th>
    <th></th>
  </tr>
<%= render @comments %>

</table>
<%=  button_to "(Re-)Import All", import_project_comments_path(@project), :confirm => "Warning: all existing comments for this project will be deleted first!", :class => 'inline' %>
<%=  button_to "Discover New", discover_comments_path(@project)  %>

<%= link_to "All Messages", project_messages_path(@project)%> |
<%= link_to "All Tasks", project_tasks_path(@project)%> |
<%= link_to "Project", project_path(@project)%>

app/views/comments/index_task.html.erb
<h1>
	All Comments for Task '<%=@task.content %>'
</h1>
<%= will_paginate @comments, :class => 'flickr_pagination' %>
<table class="url-list sortable">
  <tr>
    <th>Author</th>
    <th>Content</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('posted_on', 'Posted') %></th>
    <th></th>
  </tr>
<%= render @comments %>

</table>
<%=  button_to "(Re-)Import All", import_task_comments_path(@task), :confirm => "Warning: all existing comments for this task will be deleted first!" %>

<%= link_to "Task", task_path(@task.id)%> |
<%= link_to "All Tasks", project_tasks_path(@task.project_id)%> |
<%= link_to "Project", project_path(@task.project_id)%>

app/views/comments/index_task_comments.html.erb
<h1>
	All Task Comments for Project '<%= @project.name %>'
</h1>
<%= will_paginate @comments, :class => 'flickr_pagination' %>
<table class="url-list sortable">
  <tr>
    <th>Author</th>
    <th>Content</th>
    <th>Task Id</th>
    <th><%= sortable('num_attachments','Attachments') %></th>
    <th><%= sortable('posted_on', 'Posted') %></th>
    <th></th>
  </tr>
<%= render @comments %>
</table>

<%= link_to "All Messages", project_messages_path(@project)%> |
<%= link_to "All Tasks", project_tasks_path(@project)%> |
<%= link_to "Project", project_path(@project)%>

app/views/comments/new.html.erb
<%= render 'edit' %>

<%= link_to "All comments", message_comments_path(@message) %>

app/views/comments/show.html.erb
<% 
actions_text = ""
@actions.each_with_index do |a,i| 
  actions_text += "#{i+1}.\t#{a}\n" 
end 
events_text = ""
@events.each_with_index do |e,i| 
  events_text += "#{i+1}.\t#{e}\n" 
end 
%>
<p>
	<% if !@comment.message.nil?%>
  <b>Message Title:</b>
  <%= @comment.message.title %>
  <% elsif !@comment.task.nil?%>
  <b>Task id:</b>
  <%= @comment.task.id %>
  <% end %>
</p>
<% if @comment.basecamp_id %>
<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>
<p>
  <b>Posted:</b>
  <%= @comment.posted_on %>
</p>
<% else %>
<p>
  <b>Created:</b>
  <%= @comment.created_at %>
</p>
<% end %>
<p>
  <b>Attachments:</b>
  <% if @comment.attachments.empty? %>
     None
  <% else
     @comment.attachments.each do |a| %>
     	<%= link_to("#{a.name} (#{a.attachment_type})", "#{a.basecamp_url}") %> |
     <%	end %>
  <% end %>
</p>
<% if @comment.basecamp_id %>
<p>
  <b>Basecamp ID:</b>
  <%= @comment.basecamp_id %>
</p>
<% end %>
<p>
  <b>Content:</b><br/>
  
<div id="wrapper">
    <ul class="tabs">
        <li><a href="javascript:void(0)" class="defaulttab"  rel="tabs1">HTML View</a></li>
        <li><a href="javascript:void(0)" rel="tabs2">Raw Content</a></li>
        <li><a href="javascript:void(0)" rel="tabs3">Stripped of Tags</a></li>
        <li><a href="javascript:void(0)" rel="tabs4">Actions (<%= @actions.count %>)</a></li>
        <li><a href="javascript:void(0)" rel="tabs5">Events (<%= @events.count %>)</a></li>
        <li><a href="javascript:void(0)"  rel="tabs6"><span id="tag-header">Tags (<%= @tags.count %>)</span></a></li>
    </ul>
  <%= render 'tags/add_tag', :id => @comment.id, :controller => "comments", :all_tags => @all_tags %>
 
    <div class="tab-content" id="tabs1"><div id="htmlpreview" class="html"><%= raw @comment.content %></div></div>
    <div class="tab-content" id="tabs2"><textarea class="raw"><%= @comment.content %></textarea> </div>
    <div class="tab-content" id="tabs3">
    	<textarea class="stripped"><%= raw strip_tags(@comment.content.gsub(/&nbsp;/i," ").gsub(/<div class=\"paragraph\_break\"/i,"&#013; &#010;<div ")) %></textarea> 
    </div>
    <div class="tab-content" id="tabs4"><textarea class="stripped"><%= actions_text %></textarea></div>
    <div class="tab-content" id="tabs5"><textarea class="stripped"><%= events_text %></textarea></div>
    <div class="tab-content" id="tabs6"><%= render 'tags/tag_list', :tags => @tags, :id => @comment.id, :controller => "comments"%>
</div>  
  


</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Message', message_path(@comment.message_id) %> |
<%= link_to 'All Comments', message_comments_path(@comment.message_id) %>

app/views/comments/tag.js.erb
<% if @added %>
	$('#tag-header').text('Tags (<%= @tags.count %>)');
	$('#tag-header').effect("highlight", {}, 3000);
	<% tag_id = @new_tag.id %>
	$('#tag-list li:last').after('<li id="<%= tag_id %>"><%= link_to @new_tag.name, tag_path(tag_id), :class => "price-tag-link" %><%= link_to "X", {:controller => "comments", :action => "remove_tag", :tag_id => tag_id}, {:id => "popup-#{tag_id}", :class => "popup", :remote => true }%>');
<% else %>
  alert('<%= @tag_message %>');
<% end %>

$("form#new-tag-form")[0].reset();	
$("#new_tag").focus();