config/routes.rb
Basecamp::Application.routes.draw do

  get "events/index"

  get "events/show"

 root :to => 'projects#index'

  resources :tags do
    collection do
      put :delete_all
    end
  end
 match 'message/:id/comments', :to => 'comments#index_message', :as => "message_comments"
 match 'message/:id/new', :to => 'messages#new', :as => "new_project_message"
 match 'project/:id/comments', :to => 'comments#index_project', :as => "project_comments"
 match 'project/:id/message_comments', :to => 'comments#index_message_comments', :as => "project_message_comments"
 match 'project/:id/task_comments', :to => 'comments#index_task_comments', :as => "project_task_comments"
 match 'task/:id/comments',    :to => 'comments#index_task', :as => "task_comments"
 match 'project/:id/messages', :to => 'messages#index', :as => "project_messages"
 match 'project/:id/events', :to => 'events#index', :as => "project_events"
 match 'project/:id/tasks',    :to => 'tasks#index', :as => "project_tasks"
 match 'projects/basecamp', :to => 'projects#index_basecamp', :as => "basecamp_projects"
 match 'message/:id/add_comment', :to => 'comments#add_comment', :as => "add_message_comment"
 match 'project/:id/disconnect',    :to => 'projects#disconnect', :as => "disconnect_project"

 resources :comments
 resources :messages
 resources :tasks
 resources :projects
 resources :words
 resources :tags
 resources :events
 resources :auths

 match 'auths/select', :to => 'auths#select'
 match 'task/:id/import', :to => 'tasks#import', :as => "import_task"
 match 'task/:id/reimport', :to => 'tasks#reimport', :as => "reimport_task"
 match 'tasks/:id/import', :to => 'tasks#import_all', :as => "import_tasks"
 match 'tasks/:id/discover', :to => 'tasks#discover', :as => "discover_tasks"
 match 'tasks/:id/destroy', :to => 'tasks#destroy', :as => "project_delete_tasks"

 match 'comment/:id/import_for_message', :to => 'comments#import_for_message', :as => "import_comments_for_message"
 match 'comment/:id/reimport', :to => 'comments#reimport', :as => "reimport_comment"
 match 'comments/:id/import', :to => 'comments#import_all', :as => "import_comments"
 match 'comments/:id/discover', :to => 'comments#discover', :as => "discover_comments"
 match 'comments/:id/tag', :to => 'comments#tag'
 match 'comment/:id/remove_tag', :to => 'comments#remove_tag', :as => "remove_comment_tag"
 match 'comments/:id/destroy_message_comments', :to => 'comments#destroy_message_comments', :as => "project_delete_message_comments"
 match 'comments/:id/destroy_task_comments', :to => 'comments#destroy_task_comments', :as => "project_delete_task_comments"
 match 'comment/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_message_comments"
 match 'comment/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_task_comments"
 match 'comment/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_message_comments"

 match 'message/:id/import', :to => 'messages#import', :as => "import_message"
 match 'message/:id/reimport', :to => 'messages#reimport', :as => "reimport_message"
 match 'messages/:id/import', :to => 'messages#import_all', :as => "import_messages"
 match 'messages/:id/reimport', :to => 'messages#reimport_all', :as => "reimport_messages"
 match 'messages/:id/discover', :to => 'messages#discover', :as => "discover_messages"
 match 'messages/:id/tag', :to => 'messages#tag'
 match 'message/:id/remove_tag', :to => 'messages#remove_tag', :as => "remove_message_tag"
 match 'messages/:id/destroy', :to => 'messages#destroy', :as => "project_delete_messages"
 
 match 'event/:id/import', :to => 'events#import', :as => "import_event"
 match 'event/:id/reimport', :to => 'events#reimport', :as => "reimport_event"
 match 'event/:id/import_all', :to => 'events#import_all', :as => "import_events"
 match 'event/:id/reimport', :to => 'events#reimport_all', :as => "reimport_events"
 match 'event/:id/discover', :to => 'events#discover', :as => "discover_events"
 match 'events/:id/destroy', :to => 'events#destroy', :as => "project_delete_events"

 match 'project/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_project_message_comments"
 match 'project/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_project_message_comments"
 match 'project/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_project_task_comments"
 match 'project/:id/discover_task_comments', :to => 'comments#discover_task_comments', :as => "discover_project_task_comments"
 match 'project/:id/import', :to => 'projects#import', :as => "import_project"
 match 'project/:id/reimport', :to => 'projects#reimport', :as => "reimport_project"
 match 'projects/import', :to => 'projects#import_all', :as => "import_projects"
 match 'projects/discover', :to => 'projects#discover', :as => "discover_projects"
 match 'project/:id/refresh_available_messages', :to => 'projects#get_available_messages', :as => "refresh_available_messages"
 match 'project/:id/refresh_available_events', :to => 'projects#get_available_events', :as => "refresh_available_events"
 match 'project/:id/refresh_available_tasks', :to => 'projects#get_available_tasks', :as => "refresh_available_tasks"
 

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :project
#  has_many :comments, :dependent => :destroy
    
  def self.get_count(proj)
    proj.events.count
  end  
  
  def self.get_bc_count(proj, from_bc = false)
    num = 0
    if proj.basecamp_id   
      if from_bc
        events = get_all_bc_events_in_project(proj)
        num = events.count
        proj.available_events = num
        proj.save!
      else
        num = proj.available_events
      end
    end
    num
  end
  
  def self.get_all_bc_events_in_project(proj)
    #Basecamp::Message.find(:all, :params => { :project_id => proj.basecamp_id }, :from => :archive)
    recs = []
    page_no = 1
    r = get_bc_records page_no, proj
    page_no += 1
    keep_getting = true
    while (keep_getting) do
      if r == nil || r.count == 0
        keep_getting = false
      else
        recs += r
        r = get_bc_records page_no, proj
        page_no += 1
      end    
    end 
#    Basecamp::Message.archive(proj.basecamp_id)
    recs
  end

  def self.get_bc_records(page_no, proj)
    Basecamp.records "calendar-entry", "/projects/#{proj.basecamp_id}/calendar_entries/calendar_events", :find => :all, :page => page_no
  end
    
  def self.import_all_from_basecamp_project(project)
    Event.destroy_all(:project_id => project.id)
    bc_list = get_all_bc_events_in_project(project)
    bc_list.each do |ev|
      event = project.events.build
      event.copy_fields_from_basecamp(ev)
      if !event.save!
        return false
      end
      #sleep 1
     end
    true
  end
    
  def self.destroy_project_events(project)
     Event.destroy_all(:project_id => project.id)
  end
  
  def self.discover_new_from_basecamp(project)
   # bc_list = Basecamp::Message.find(:all, :params => { :project_id => project.basecamp_id}, :from => :archive)
   bc_list = get_all_bc_events_in_project(project)
   bc_list.each do |ev|
      if !find_by_basecamp_id(ev.id)
        event = project.events.build
        event.copy_fields_from_basecamp(ev)
        if !event.save!
          return false
        end
        sleep 1
        #Comment.discover_new_from_basecamp_message(bcm.id)
       
      end 
    end
    true
  end
      
  def copy_fields_from_basecamp(basecamp_event)
    self.title = basecamp_event.title
    self.start_at = basecamp_event.due_at
    self.created_on = basecamp_event.created_on
    self.basecamp_id = basecamp_event.id
    self.creator = basecamp_event.creator_name
   true
  end  


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include   ApplicationHelper

  helper_method :sort_column, :sort_direction

  def index
    @project = Project.find(params[:id])    

    @per_page = params[:per_page] ||  20
    order_str = sort_column + " "  + sort_direction
    @events = @project.events.order(order_str).page(params[:page]).per_page(@per_page)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def new
    @project = Project.find(params[:id])
    @event = Event.new
  end
  
  def create
    @project = Project.find(params[:id])
    @event = @project.events.build(params[:event])
    if !@event.save!
      flash.now[:error] = "Error creating event"
      render 'new'
    else
      redirect_to project_events_path(@project), :notice => "Created event"     
    end
  end
  
  def edit
    @event = Event.find(params[:id])  
    @project = @event.project
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash.now[:success] = "Updated event"
    else
      flash.now[:error] = "Error updating event"
    end
    render 'edit'
  end

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  def import_all
    project = Project.find(params[:id])
    if Event.import_all_from_basecamp_project(project)
      flash[:success] = "Imported events successfully"
    else
      flash[:error] = "There was a problem importing the events"
    end
    redirect_to project_path(project.id)
  end
 
  def import
    event = copy_event_from_basecamp Basecamp::Post.find(params[:id])
    if event.save!
      flash[:success] = "Imported event successfully"
    else
      flash[:error] = "There was a problem importing the event"
    end
    redirect_to project_events_path(event.project_id)
  end
  
  def reimport
    event = Event.find(params[:id])
    event.copy_fields_from_basecamp(Basecamp::Event.find(event.basecamp_id))    
    if event.save!
      flash[:success] = "Re-Imported event successfully"
    else
      flash[:error] = "There was a problem re-importing the event"
    end
    redirect_to project_events_path(event.project_id)
  end
  
  def destroy
    project = Project.find(params[:id])
    Event.destroy_project_events(project)    
    redirect_to project_path(project), :notice => "Removed events"     
  end
  
  def discover
    project = Project.find(params[:id])
    startnum = project.events.count
    if !Event.discover_new_from_basecamp(project)
      redirect_to project_events_path(params[:id]), :error => "Error importing new events"
    end
    additional_num = project.events.count-startnum
    redirect_to project_path(params[:id]), :notice => additional_num > 0 ? "Successfully imported #{additional_num} new events" : "No new events to import"
  end  
  
  private
  
    def sort_column
      Event.column_names.include?(params[:sort]) ? params[:sort] : "created_on"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/events_helper.rb
module EventsHelper
  
   include ActionView::Helpers::SanitizeHelper 

end

app/views/events/_edit.html.erb
<%= form_for @event do |f| %>

	<%= f.label 'Title' %>	
	<%= f.text_field :title %><br/>
	<%= f.label 'Date' %>	
	<%= f.datetime :start_at %><br/>
	<%= f.submit %>
<%= hidden_field_tag "id", @project.id %>
	
<% end %>

app/views/events/_event.html.erb
  <tr>
<% if event.basecamp_id %>
    <td ><%= event.id.nil? ? event.title : link_to(event.title, event_path(event)) %></td>
    <td style="width: 150px"><%= event.start_at.to_formatted_s(:short) %></td>
    <td style="width: 150px"><%= event.created_at.to_formatted_s(:short) %></td>
    <td><%= event.id.nil? ? link_to('Import', import_event_path(event)) : link_to('Re-Import', reimport_event_path(event)) %></td>
<% else %>
    <td><%= link_to(event.title, event_path(event)) %></td>
    <td style="width: 150px"><%= event.created_at.to_formatted_s(:long) %></td>
    <td style="width: 150px"><%= event.updated_at.to_formatted_s(:long) %></td>
<% end %>
  </tr>

app/views/events/edit.html.erb
<%= render 'edit', :many => false %>

<%= link_to "All events", project_events_path(@project) %>

app/views/events/index.html.erb
<h1>Events for Project '<%=@project.name%>'</h1>


<%= will_paginate @events, :class => 'flickr_pagination' %>

<table class="cloud-and-table">
	<tr>
   			<th id="list-header">Title</th>
			<th><%= sortable("start_at", "Date") %> </th>
    			<% if @project.basecamp_id %>
    				<th><%= sortable("created_on", "Created") %> </th>
    			<% else %>
      				<th><%= sortable("created_at", "Created") %> </th>
      				<th><%= sortable("updated_at", "Updated") %> </th>
				<% end %>
    			<th></th>
  			</tr>
				<%= render @events %>
			</table>
		</td>	
	</tr>
</table>
<% if @project.basecamp_id %>
<%=  button_to "(Re-)Import All", import_messages_path(@project), :confirm =>"Are you sure?  All events for this project will be deleted first...", :class => 'inline' %>
<%=  button_to "Discover new", discover_events_path(@project)%>
<%= link_to "Project", project_path(@project)%> |
<%= link_to "All Projects", basecamp_projects_path %> 
<% else %>
<%= button_to "Create Event", new_project_event_path(@project.id), :method => 'get' %>
<%= link_to "Project", project_path(@project)%> |
<%= link_to "All Projects", projects_path %> 
<% end %>

app/views/events/new.html.erb
<%= render 'edit' %>

<%= link_to "All events", project_events_path(@project) %>

app/views/events/show.html.erb
<table>

<tr>
	<td><b>Title:</b></td>
	<td><%= @event.title %></td>
</tr>

<% if @event.basecamp_id %>
<tr>
	<td><b>Creator:</b></td>
  	<td><%= @event.creator %></td>
</tr>
<tr>
	<td><b>Created:</b></td>
  	<td><%= @event.created_on %></td>
</tr>
<% else %>
<tr>
	<td><b>Created:</b></td>
  	<td><%= @event.created_at %></td>
</tr>
<% end %>
<tr>
	<td><b>Event date:</b></td>
  	<td><%= @event.start_at %></td>
</tr>
<% if @event.basecamp_id %>
<tr>
	<td><b>Basecamp ID:</b></td>
  	<td><%= @event.basecamp_id %></td>
</tr>
<% end %>
</table>
</p>



<%= link_to 'All Events', project_events_path(@event.project_id) %>