config/routes.rb
Basecamp::Application.routes.draw do

  get "events/index"

  get "events/show"

 root :to => 'projects#index'

  resources :tags do
    collection do
      put :delete_all
    end
  end
 match 'message/:id/comments', :to => 'comments#index_message', :as => "message_comments"
 match 'message/:id/new', :to => 'messages#new', :as => "new_project_message"
 match 'project/:id/comments', :to => 'comments#index_project', :as => "project_comments"
 match 'project/:id/message_comments', :to => 'comments#index_message_comments', :as => "project_message_comments"
 match 'project/:id/task_comments', :to => 'comments#index_task_comments', :as => "project_task_comments"
 match 'task/:id/comments',    :to => 'comments#index_task', :as => "task_comments"
 match 'project/:id/messages', :to => 'messages#index', :as => "project_messages"
 match 'project/:id/events', :to => 'events#index', :as => "project_events"
 match 'project/:id/tasks',    :to => 'tasks#index', :as => "project_tasks"
 match 'projects/basecamp', :to => 'projects#index_basecamp', :as => "basecamp_projects"
 match 'message/:id/add_comment', :to => 'comments#add_comment', :as => "add_message_comment"
 match 'project/:id/disconnect',    :to => 'projects#disconnect', :as => "disconnect_project"

 resources :comments
 resources :messages
 resources :tasks
 resources :projects
 resources :words
 resources :tags
 resources :events
 resources :auths

 match 'auths/select', :to => 'auths#select'
 match 'task/:id/import', :to => 'tasks#import', :as => "import_task"
 match 'task/:id/reimport', :to => 'tasks#reimport', :as => "reimport_task"
 match 'tasks/:id/import', :to => 'tasks#import_all', :as => "import_tasks"
 match 'tasks/:id/discover', :to => 'tasks#discover', :as => "discover_tasks"
 match 'tasks/:id/destroy', :to => 'tasks#destroy', :as => "project_delete_tasks"

 match 'comment/:id/import_for_message', :to => 'comments#import_for_message', :as => "import_comments_for_message"
 match 'comment/:id/reimport', :to => 'comments#reimport', :as => "reimport_comment"
 match 'comments/:id/import', :to => 'comments#import_all', :as => "import_comments"
 match 'comments/:id/discover', :to => 'comments#discover', :as => "discover_comments"
 match 'comments/:id/tag', :to => 'comments#tag'
 match 'comment/:id/remove_tag', :to => 'comments#remove_tag', :as => "remove_comment_tag"
 match 'comments/:id/destroy_message_comments', :to => 'comments#destroy_message_comments', :as => "project_delete_message_comments"
 match 'comments/:id/destroy_task_comments', :to => 'comments#destroy_task_comments', :as => "project_delete_task_comments"
 match 'comment/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_message_comments"
 match 'comment/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_task_comments"
 match 'comment/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_message_comments"

 match 'message/:id/import', :to => 'messages#import', :as => "import_message"
 match 'message/:id/reimport', :to => 'messages#reimport', :as => "reimport_message"
 match 'messages/:id/import', :to => 'messages#import_all', :as => "import_messages"
 match 'messages/:id/reimport', :to => 'messages#reimport_all', :as => "reimport_messages"
 match 'messages/:id/discover', :to => 'messages#discover', :as => "discover_messages"
 match 'messages/:id/tag', :to => 'messages#tag'
 match 'message/:id/remove_tag', :to => 'messages#remove_tag', :as => "remove_message_tag"
 match 'messages/:id/destroy', :to => 'messages#destroy', :as => "project_delete_messages"
 
 match 'event/:id/import', :to => 'events#import', :as => "import_event"
 match 'event/:id/reimport', :to => 'events#reimport', :as => "reimport_event"
 match 'event/:id/import_all', :to => 'events#import_all', :as => "import_events"
 match 'event/:id/reimport', :to => 'events#reimport_all', :as => "reimport_events"
 match 'event/:id/discover', :to => 'events#discover', :as => "discover_events"
 match 'events/:id/destroy', :to => 'events#destroy', :as => "project_delete_events"

 match 'project/:id/import_message_comments', :to => 'comments#import_message_comments', :as => "import_project_message_comments"
 match 'project/:id/discover_message_comments', :to => 'comments#discover_message_comments', :as => "discover_project_message_comments"
 match 'project/:id/import_task_comments', :to => 'comments#import_task_comments', :as => "import_project_task_comments"
 match 'project/:id/discover_task_comments', :to => 'comments#discover_task_comments', :as => "discover_project_task_comments"
 match 'project/:id/import', :to => 'projects#import', :as => "import_project"
 match 'project/:id/reimport', :to => 'projects#reimport', :as => "reimport_project"
 match 'projects/import', :to => 'projects#import_all', :as => "import_projects"
 match 'projects/discover', :to => 'projects#discover', :as => "discover_projects"
 match 'project/:id/refresh_available_messages', :to => 'projects#get_available_messages', :as => "refresh_available_messages"
 match 'project/:id/refresh_available_events', :to => 'projects#get_available_events', :as => "refresh_available_events"
 match 'project/:id/refresh_available_tasks', :to => 'projects#get_available_tasks', :as => "refresh_available_tasks"
 

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :messages, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :tasks, :dependent => :destroy
  has_many :message_tags, :through => :messages, :source => :tags
  has_many :message_comments, :through => :messages, :source => :comments
  has_many :task_comments, :through => :tasks, :source => :comments
  has_many :message_comment_tags, :through => :message_comments, :source => :tags
  has_many :task_comment_tags, :through => :task_comments, :source => :tags
  
  def self.import_all_from_basecamp
    destroy_all(:condition => [ "basecamp_id NOT NULL" ])
    projects = Basecamp::Project.find(:all)
    projects.each do |p|
      if !find_by_basecamp_id(p.id)
        proj = new
        proj.copy_fields_from_basecamp(p)
        if !proj.save!
          return false
        end
      end 
    end
    true
  end
  
  def self.discover_new_from_basecamp
    ps = Basecamp::Project.find(:all)
    num_new=0
    ps.each do |p|
      if !find_by_basecamp_id(p.id)
        proj = new
        num_new+=1
        proj.copy_fields_from_basecamp(p)
        if !proj.save!
          return -1
        end
      end 
    end
    num_new
  end
  
  def copy_fields_from_basecamp basecamp_project
    self.name = basecamp_project.name
    self.created_on = basecamp_project.created_on
    self.last_changed_on = basecamp_project.last_changed_on
    self.status = basecamp_project.status
    self.company_name = basecamp_project.company.name
    self.basecamp_id = basecamp_project.id
    self.announcement = basecamp_project.announcement
  end  
  
  def disconnect_project
    self.basecamp_id = nil    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  include ApplicationHelper
  before_filter :authenticate_api, :only => [:index_basecamp, :discover]
  before_filter :start_session
  
  def index
    @projects = Project.where("basecamp_id IS NULL")
    @bc_projects = Project.where("basecamp_id IS NOT NULL")
    #@auths = Auth.all
  end

  def new
    @project = Project.new
  end
  
  def create
    project = Project.new(params[:project])
    if !project.save!
      flash.now[:error] = "Error creating project"
      render 'new'
    else
      redirect_to projects_path, :notice => "Created project"     
    end
  end
  
  def edit
    @project = Project.find(params[:id])  
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash.now[:success] = "Updated project"
    else
      flash.now[:error] = "Error updating project"
    end
    render 'edit'
  end
  
  def show
    @project = Project.find(params[:id])
    @num_messages = @project.messages.count
    @num_events = @project.events.count
    @num_bc_messages = Message.get_bc_count(@project)
    @num_bc_events = Event.get_bc_count(@project)
    @num_message_comments = @project.message_comments.count
    @num_task_comments = @project.task_comments.count
    @num_bc_comments = 99#Comment.get_bc_count(@project)
    @num_tasks = @project.tasks.count
    @num_bc_tasks = Task.get_bc_count(@project)

  end

  def disconnect
    project = Project.find_by_basecamp_id(params[:id])
    project.disconnect_project
    if project.save!
      flash[:success] = "Disconnected project from basecamp"
    end
    redirect_to projects_path
    
  end
  
  def get_available_messages
    project = Project.find(params[:id])
    Message.get_bc_count(project, true)
    redirect_to project_path(project)
  end

  def get_available_events
    project = Project.find(params[:id])
    Event.get_bc_count(project, true)
    redirect_to project_path(project)
  end

  def get_available_tasks
    project = Project.find(params[:id])
    Task.get_bc_count(project, true)
    redirect_to project_path(project)
  end
  
  def import_all
    if !Project.import_all_from_basecamp
      redirect_to root_path, :error => "Error importing all projects"
    end
    redirect_to root_path, :notice => "Successfully imported all projects"
  end  

  def discover
    #startnum = Project.all.count
    num_new = Project.discover_new_from_basecamp
    if num_new<0
      redirect_to root_path, :error => "Error importing new projects"
    end
    #additional_num = Project.all.count-startnum
    redirect_to root_path, :notice => num_new > 0 ? "Successfully imported #{num_new} new projects" : "No new projects to import"
  end  
  
  def import
    proj = Project.new
    proj.copy_fields_from_basecamp(Basecamp::Project.find(params[:id]))
    if proj.save!
      flash[:success] = "Imported project successfully"
    else
      flash[:error] = "There was a problem importing the project"
    end
    redirect_to projects_path
  end
  
  def reimport
    project = Project.find(params[:id])
    project.copy_fields_from_basecamp(Basecamp::Project.find(project.basecamp_id))
    if project.save!
      flash[:success] = "Imported project successfully"
    else
      flash[:error] = "There was a problem importing the project"
    end
    redirect_to projects_path
  end
  
  
  private



end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_edit.html.erb
<%= form_for @project do |f| %>

	<%= f.label 'Name' %>	
	<%= f.text_field :name %><br/>
	<%= f.label 'Description' %>	
	<%= f.text_area :description %><br/>
	<%= f.submit %>
	
<% end %>

app/views/projects/_index.html.erb
<h2>Projects</h2>
<table class="url-list sortable">
	<tr>
		<th>Name</th>
		<th>Created</th>
		<th>Updated</th>
		<th># Messages</th>
		<th># Tags</th>
	</tr>
<%= render projects %>
</table>

<%= button_to 'Create new project', new_project_path,  :method => 'get'%>

app/views/projects/_index_bc.html.erb
<h2>Basecamp Projects</h2>
<table class="url-list sortable">
	<tr>
		<th>Name</th>
		<th>Created</th>
		<th>Updated</th>
		<th>Status</th>
		<th>Company</th>
		<th></th>
		<th></th>
	</tr>
<%= render projects %>
</table>
<%= button_to '(Re-)Import All from basecamp', import_projects_path, :class => "inline", :confirm => "Are you sure?  All project data will be deleted first..." %>
<%= button_to 'Load new projects from basecamp', discover_projects_path, :class => "inline" %>

app/views/projects/_project.html.erb
<tr>
<% if project.basecamp_id.nil? %>
	<td><%= link_to(project.name, project_path(project)) %></td>
	<td><%= project.created_at.to_formatted_s(:long) %></td>
	<td><%= project.updated_at.to_formatted_s(:long) %></td>
	<td><%= project.messages.count %></td>
	<td> <%= project.message_tags.count if !project.message_tags.nil? %> </td>
<% else %>
	<td><%= project.id.nil? ? project.name : link_to(project.name, project_path(project)) %></td>
	<td><%= project.created_on.to_formatted_s(:long) %></td>
	<td><%= project.last_changed_on.nil? ? "Never" : project.last_changed_on.to_formatted_s(:long) %></td>
	<td><%= project.status %></td>
	<td><%= project.company_name %></td>
	<td ><%= project.id.nil? ? button_to('Import', import_project_path(project.basecamp_id)) : button_to('Re-import', reimport_project_path(project)) %></td>
	<td><%= button_to('Disconnect', disconnect_project_path(project.basecamp_id), :data => {:confirm => 'Are you sure?'})  if !project.id.nil? %></td>
<% end %>
</tr>
 

app/views/projects/edit.html.erb
<%= render 'edit', :many => false %>

<%= link_to "All projects", projects_path %>

app/views/projects/index.html.erb
<%= render 'index', :projects => @projects %>
<%= render 'index_bc', :projects => @bc_projects %>

app/views/projects/index_basecamp.html.erb
<h2>Projects</h2>
<table class="url-list sortable">
	<tr>
		<th>Name</th>
		<th>Created</th>
		<th>Updated</th>
		<th>Status</th>
		<th>Company</th>
		<th></th>
	</tr>
<%= render @projects %>
</table>
<%= button_to '(Re-)Import All from basecamp', import_projects_path, :class => "inline", :confirm => "Are you sure?  All project data will be deleted first..." %>
<%= button_to 'Load new projects from basecamp', discover_projects_path, :class => "inline" %>
<%= button_to 'Create new project', new_project_path,  :method => 'get'%>

app/views/projects/new.html.erb
<%= render 'edit' %>

<%= link_to "All Projets", projects_path %>

app/views/projects/show.html.erb
<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<% if @project.basecamp_id %> 
<p>
  <b>Announcement:</b>
  <%= @project.announcement %>
</p><p>
  <b>Created:</b>
  <%= @project.created_on %>
</p>
<p>
  <b>Last updated:</b>
  <%= @project.last_changed_on %>
</p>
<p>
  <b>Status:</b>
  <%= @project.status %>
</p>
<p>
  <b>Basecamp id:</b>
  <%= @project.basecamp_id %>
</p>

<% else %>
<p>
  <b>Description:</b>
  <%= @project.description %>
</p><p>
  <b>Created:</b>
  <%= @project.created_at %>
</p>
<p>
  <b>Last updated:</b>
  <%= @project.updated_at %>
</p>
<% end %>
<p>
  <b>Messages:</b>
  <%= link_to(@num_messages, project_messages_path(@project.id)) %> (<%= @num_bc_messages %> available - <%= link_to "Refresh", refresh_available_messages_path(@project) %>) |
  <%= link_to("Import all", import_messages_path(@project.id))%> |
  <%= link_to("Import new", discover_messages_path(@project.id))%> |
  <%= link_to("Remove all", project_delete_messages_path(@project.id))%>
</p>
<p>
  <b>Message Comments:</b>
  <%= link_to(@num_message_comments, project_message_comments_path(@project.id)) %> 
  <%= link_to("Import all", import_message_comments_path(@project.id))%> |
  <%= link_to("Import new", discover_message_comments_path(@project.id))%> |
  <%= link_to("Remove all", project_delete_message_comments_path(@project.id))%>
</p>  
  <b>Tasks:</b>
  <%= link_to(@num_tasks, project_tasks_path(@project.id)) %> (<%= @num_bc_tasks %> available - <%= link_to "Refresh", refresh_available_tasks_path(@project) %>) |
  <%= link_to("Import all", import_tasks_path(@project.id))%> |
  <%= link_to("Import new", discover_tasks_path(@project.id))%> |
  <%= link_to("Remove all", project_delete_tasks_path(@project.id))%>
</p>
<p>
  <b>Task Comments:</b>  
  <%= link_to(@num_task_comments, project_task_comments_path(@project.id)) %> 
  <%= link_to("Import all", import_task_comments_path(@project.id))%>   |
  <%= link_to("Remove all", project_delete_task_comments_path(@project.id))%>
</p>
<p>
  <b>Events:</b>
  <%= link_to(@num_events, project_events_path(@project.id)) %> (<%= @num_bc_events %> available - <%= link_to "Refresh", refresh_available_events_path(@project) %>) |
  <%= link_to("Import all", import_events_path(@project.id))%> |
  <%= link_to("Import new", discover_events_path(@project.id))%> |
  <%= link_to("Remove all", project_delete_events_path(@project.id))%>
</p>
<%= link_to 'All Projects', projects_path %>